name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev cmake libffi-dev build-essential

      - name: Install Stable Build Tools
        run: |
          pip install --upgrade pip
          pip install "cython<3.0.0" wheel
          pip install "kivy>=2.2.0"
          pip install git+https://github.com

      - name: Generate Empty Buildozer To Force Accept Licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          # الموافقة المسبقة على شروط جوجل للأندرويد
          yes | buildozer android debug || true

      - name: Clean and Build Final APK
        run: |
          buildozer clean
          yes | buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: bin/*.apk
